

# 빌드 설정
[build]
  command = "# npm run build" # 빌드 명령어 (필요한 경우 주석 해제)
  functions = "netlify/functions"
  publish = "."

# 개발 서버 설정  
[dev]
  command = "# npm run dev" # 개발 서버 명령어 (필요한 경우 주석 해제)
  port = 8888
  targetPort = 3000
  framework = "#custom"

# CORS 헤더 설정
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    
# 프록시 설정 (필요한 경우)
[[redirects]]
  from = "/api/tourAPI/*"
  to = "http://apis.data.go.kr/B551011/KorService2/:splat"
  status = 200
  force = true